### Test API Register
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "oke123",
    "email": "ajasaja@example.com",
    "password": "12345678",
    "confPassword": "12345678"
   
}

### Test API login
POST https://authv2.lifeforcode.net/login
Content-Type: application/json

{

    "email": "amin@gmail.com",
    "password": "12345678"
   
}
### Test API l
GET  https://authv2.lifeforcode.net/transaksi-keluar
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJuYW1lIjoiQW1pbmFoIiwiZW1haWwiOiJhbWluQGdtYWlsLmNvbSIsImlhdCI6MTcyMTQ4NDMyNCwiZXhwIjoxNzIxNDg0MzM5fQ.QIIXeZnH60YtsjttjxQERC2DCoNAQ3PlqKALT15QVYo

